Feature/bronco
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #10
Opened 2017-03-03 12:23 UTC by janfix

1. Correction norme présentation du code
2. Signature Wiquid fixed
3. use strict
4. deletion commented code
5. Non-Anonymous function in AMD
6. $Container.find
7. less call on jQuery objects

2017-03-28 13:42 UTC, ssipasseuth requested changes
3 petits points à revoir

2017-03-28 13:42 UTC, ssipasseuth commented on views/js/pciCreator/dev/bronco/pciCreator.js
> +            $("div .bronco").each(function(index, el) {
code à supprimer

2017-03-28 13:42 UTC, ssipasseuth commented on views/js/pciCreator/dev/bronco/runtime/css/bronco.css
> +@-moz-document url-prefix() {
@-moz-document url-prefix() : à quoi ça sert ?

2017-03-28 13:42 UTC, ssipasseuth commented on views/js/pciCreator/dev/bronco/runtime/css/bronco.css
> +    .qti-customInteraction .broncoinput[type=range]::-ms-fill-upper {
.broncoinput en attaché ...

2017-03-29 12:52 UTC, janfix commented on views/js/pciCreator/dev/bronco/runtime/css/bronco.css
> +@-moz-document url-prefix() {
je vire

2017-03-29 12:52 UTC, janfix commented on views/js/pciCreator/dev/bronco/runtime/css/bronco.css
> +    .qti-customInteraction .broncoinput[type=range]::-ms-fill-upper {
corrigé !

2017-03-29 13:35 UTC, merged