Feature/circuit
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #11
Opened 2017-03-03 12:23 UTC by janfix

1. Correction norme présentation du code
2. Signature Wiquid fixed
3. use strict
4. deletion commented code
5. Non-Anonymous function in AMD
6. $Container.find
7. less call on jQuery objects

2017-03-28 14:59 UTC, ssipasseuth requested changes

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/circuit.amd.js
> +                value =  document.getElementById('idCanvas_1').innerHTML  + 'historique des mouvements : ' + $container.find('.answcircuit').text();
utilisation de id à remplacer

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/css/circuit.css
> +.circuit ul.compact {
ne pas oublier le name space .qti-customInteraction .circuit

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/renderer.js
> +            renderChoices(id, $(container), config);
cette fonction semble inutile, à supprimer ?

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/renderer.js
> +
fonction vide : est-ce normal ?
si oui, la supprimer ?

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/renderer.js
> +    }
idem

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +                        /*this.drawing[1].translate(-5, -5);*/
code commenté suspect: si inutile, à supprimer

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/pciCreator.js
> +        $("div .circuit").each(function(index, el) {
code à supprimer

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +}); // close define.
remarque générale sur tout le fichier : 
1. attention au **hoisting** des variables
2. pensez à nommer **toutes** vos fonctions.

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +                $(target).add(target).each(function(k,v) {
selecteur global

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +                $(target).add(target).each(function(k,v) {
d'ailleurs drôle de selection.. pourquoi ajouter un element à lui même ?

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +                    wordArr = wordArr.concat(words.filter(function(n){return n.trim();}));
il n'y a pas un moyen plus simple d'obtenir le contenu du text ?
la complexité crée potentiellement un nid à bugs

2017-03-28 14:59 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +}); // close define.
ne outre, la déclaration des composants ferait mieux d'être dans des fichiers séparé pour la clarté du code : séparer la définition des objets et leur usages.

2017-03-29 07:36 UTC, janfix commented on views/js/pciCreator/dev/circuit/runtime/js/renderer.js
> +            renderChoices(id, $(container), config);
J'ai supprimé tout. pour ne laisser que wcircuit.js

2017-03-29 07:42 UTC, janfix commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +                $(target).add(target).each(function(k,v) {
Je cumule les noms  pour retracer l'historique des manipulations

2017-03-29 08:50 UTC, janfix commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +                    wordArr = wordArr.concat(words.filter(function(n){return n.trim();}));
il faut que je creuse

2017-03-29 10:07 UTC, janfix commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +}); // close define.
Je viens de nommer toutes les fonctions et vérifier les hoisting. C'est vrai que la séparation des composants est une meilleure solution, et c'est comme cela que j'ai fait la maquette HTML, mais comme je redoutais la gestion des fichiers js dans les PCI, j'ai décidé de les fusionner en faisant des compartiments avec des annotations, et pensant que cela servait la performance. Du coup pour le hoisting en fin de fichier, c'est un peu à la va comme je te pousse...

2017-03-29 12:00 UTC, janfix commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +}); // close define.
Est-ce que cela convient si on reste sur un fichier unique ?

2017-03-29 12:11 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/js/wcircuit.js
> +}); // close define.
ok

2017-03-29 14:17 UTC, ssipasseuth commented
J'ai un problème blocant en jouant avec les différents composants (cf. console javascript)
<img width="1669" alt="wiquid_circuit_error" src="https://cloud.githubusercontent.com/assets/8425344/24458890/817a8b36-149a-11e7-81a6-3dd028ec2ff1.png">

Autre soucis:
1. Je n'arrive pas toujours à savoir si un élément est déplaçable ou non : je suggère ainsi de changer le curseur de la souris vers "pointer" lorsqu'un élément est déplaçable.
2. Le déplacement ne peut être initialisé lorsque mousedown est sur une lettre, ex: M pour le moteur, G pour le générateur...

2017-03-30 06:41 UTC, ssipasseuth reviewed
encore un petit souci...

2017-03-30 06:41 UTC, ssipasseuth commented on views/js/pciCreator/dev/circuit/runtime/circuit.amd.js
> +                value =  $('.simspace').html()  + 'historique des mouvements : ' + $container.find('.answcircuit').text();
je viens de voir encore un selecteur global

2017-03-30 07:27 UTC, merged