Script install  / update et modifications :
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #16
Opened 2017-03-03 12:34 UTC by janfix

1. Correction norme présentation du code
2. Signature Wiquid fixed
3. use strict
4. deletion commented code
5. Non-Anonymous function in AMD
6. $Container.find
7. less call on jQuery objects
8. Unique ID with Lodash for Raphael Canvas

2017-03-28 16:00 UTC, ssipasseuth requested changes
Code difficile à comprendre à clarifier, n'hésitez pas à documenter vos codes.
Il y a aussi un problème de chargement de Raphael à vérifier ainsi que d'autres détails à revoir.

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/pciCreator.js
> +            // REM : Activate if multiple instance are not possible.
à supprimer complètement

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/css/base.css
> +
le fichier views/js/pciCreator/dev/lentilles/runtime/css/img/bg.png ne semble pas utilisé, donc fichier à supprimer ?

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +                    //cellvalidator(cellactiv);
code commenté à retirer ?

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/raphael.json.js
> +		define(["raphael"], function(Raphael) {
Problème de chargement ici. il va chercher à charger Raphael global et non celui indiqué par votre PCI: ./runtime/js/raphael.min.js
Pour tester vérifier si c'est bien le même Raphael utilisé, vous pouvez essayer define(['raphael', 'lentilles/runtime/js/raphael.min'], function(R1, R2){ //puis vérifier si c'est le même object ou pas   })

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/rtext_edit.js
> +		define(["raphael"], function(Raphael) {
de même ici: problème de chargement ici. il va chercher à charger Raphael global et non celui indiqué par votre PCI.

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +                moveFnc = function(dx, dy) {
fonction à nommer

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +            $('.repgraphor').html(JSON.stringify(graphjson));
selecteur global

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +        Raphael.st.draggable2 = function() {
différence entre draggable2 et draggable ? (draggable2 ne semble pas utilisé)

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +        Raphael.st.draggable = function() {
Un peu tard pour maintenant, mais à considérer pour la prochaine fois: étendre des objets globaux est dangereux car vous ne maitrisez pas le cycle de vie de l'objet Raphael.st ou Raphael. Il vaut mieux ajouter le comportement désiré en utilisant l'API sans la modifier... à moins que ce soit une pratique prévu par l'auteur ?

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +    }
remarque général pour ce fichier:
1. attention à bien refléter le hoisting des variables
2. il est préférable d'isoler la définition des fonctions d'un coté et l'usage d'un autre

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/rtext_edit.js
> +		console.log("TEXT EDIT LOAD TEST");
console.log ?

2017-03-28 16:00 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/js/rtext_edit.js
> +				console.log(this.input.value);*/
console.log ??

2017-03-30 08:23 UTC, janfix commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +        Raphael.st.draggable2 = function() {
scorie !

2017-03-30 08:25 UTC, janfix commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +        Raphael.st.draggable = function() {
Si je me rappelle bien, impossible de dragger un set autrement que par cette extension, sinon le drag fonctionne élément par élément

2017-03-30 09:13 UTC, janfix commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +                moveFnc = function(dx, dy) {
les 3 sont nommées

2017-03-30 09:15 UTC, janfix commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +    }
Je reprends le hoisting

2017-03-30 10:14 UTC, janfix commented on views/js/pciCreator/dev/lentilles/runtime/js/raphael.json.js
> +		define(["raphael"], function(Raphael) {
J'avais essayé de charger Raphael avec le path depuis lentilles, mais impossible de le charger. Pareil dans votre proposition, R2  n'est pas défini.

2017-04-04 14:53 UTC, ssipasseuth requested changes
Des problèmes de style mineurs. Il faut surtout rectifier le selecteur global après c'est bon pour une première version.

2017-04-04 14:53 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/lentilles.amd.js
> +//            var assetManager = qtiCustomInteractionContext.getAssetResolver(this.getTypeIdentifier());//that would introduce dependency between the asset manager and global pci runtime context
code inutile à supprimer

2017-04-04 14:53 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/lentilles.amd.js
> +                            var cellcontent = $("."+celladdress).text();
selection globale

2017-04-04 14:53 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/lentilles.amd.js
> +                    for (var j = 1; j < 12; j++) {
hoisting

2017-04-04 14:53 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/lentilles.amd.js
> +                            var celladdress = collum[i]+j;
hoisting

2017-04-04 14:53 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/lentilles.amd.js
> +                            var cellcontent = $("."+celladdress).text();
hoisting

2017-04-04 14:53 UTC, ssipasseuth commented on views/js/pciCreator/dev/lentilles/runtime/lentilles.amd.js
> +                // Todo : multiple instance of the PCI - Grab results with a foreach
ce commentaire est toujours d'actualité ?

2017-04-04 16:36 UTC, janfix commented on views/js/pciCreator/dev/lentilles/runtime/js/renderer.js
> +    }
OK c'est fait mais j'ai fait 2 grands groupes : l'un pour le tableur et l'autre pour le graphique Raphael

2017-04-04 16:39 UTC, janfix commented on views/js/pciCreator/dev/lentilles/runtime/lentilles.amd.js
> +                // Todo : multiple instance of the PCI - Grab results with a foreach
non vieux truc

2017-04-05 08:53 UTC, merged