script install et update et modifications... :->
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #17
Opened 2017-03-03 12:35 UTC by janfix

1. Correction norme présentation du code
2. Signature Wiquid fixed
3. use strict
4. deletion commented code
5. Non-Anonymous function in AMD
6. $Container.find
7. less call on jQuery objects

2017-03-27 11:52 UTC, ssipasseuth requested changes
presque aussi, quelques ajustements à vérifier

2017-03-27 11:52 UTC, ssipasseuth commented on views/js/pciCreator/dev/maraissalant/runtime/css/maraissalant.css
> +@-webkit-keyframes rotation {
il faudrait aussi scoper le nom des animations, sinon il pourrait avoir un conflit au niveau global, surtout pour un nom aussi commun qu'est "rotation*

2017-03-27 11:52 UTC, ssipasseuth commented on views/js/pciCreator/dev/maraissalant/runtime/css/maraissalant.css
> +@-moz-keyframes rotation {
idem

2017-03-27 11:52 UTC, ssipasseuth commented on views/js/pciCreator/dev/maraissalant/runtime/js/renderer.js
> +            if(obj.id=="item-editor-scroll-inner"){
ce code est-il utilisé ? pourquoi ?
Le runtime d'une PCI n'a pas connaissance de d'éditeur d'item en règle générale.
Il serait sage de retirer tout ce code.

2017-03-27 11:52 UTC, ssipasseuth commented on scripts/update/Updater.php
> +            $this->setVersion('1.1.0');
n'oubliez pas d'incrémenter le numéro de version dans le manifest.php pour correspondre à cette version sinon l'update script ne sera pas exécuté

2017-03-27 11:52 UTC, ssipasseuth commented on views/js/pciCreator/dev/maraissalant/runtime/js/renderer.js
> +                $({ height: $('.joker').attr('height',0) })
$('.joker') selection global

2017-03-27 11:52 UTC, ssipasseuth commented on scripts/update/Updater.php
> +            call_user_func(new RegisterPciMaraissalant(), ['0.1.0']);
il vaut mieux aussi indiquer la version de la PCI qui figure dans votre manifest pciCreator.json

2017-03-28 08:19 UTC, janfix commented on views/js/pciCreator/dev/maraissalant/runtime/js/renderer.js
> +            if(obj.id=="item-editor-scroll-inner"){
J'avais fait un test pour modifier l'aspect des PCI dans la zone d'édition, car elles pouvaient dépasser le cadre ou être mal affichée en édition.

2017-03-28 08:36 UTC, merged