scripts update et install + modifications :
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #20
Opened 2017-03-03 12:37 UTC by janfix

1. Correction norme présentation du code
2. Signature Wiquid fixed
3. use strict
4. deletion commented code
5. Non-Anonymous function in AMD
6. $Container.find
7. less call on jQuery objects
8. Unique ID with Lodash for Raphael Canvas

2017-03-27 11:50 UTC, ssipasseuth requested changes
presque ok, encore quelques ajustements à voir

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/creator/widget/states/states.js
> +    return factory.createBundle(states, arguments, ['answer', 'correct', 'map']);
use strict

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/pciCreator.js
> +                   $(".widget-box").remove();
selecteur jquery global

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/pciCreator.js
> +                   $(".grid-row").remove();
selecteur jquery global

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/runtime/css/train.css
> +.qti-customInteraction .trainvache #commande {
l'utilisation de l'identifiant est-il justifié ici ?

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/runtime/css/train.css
> +.qti-customInteraction .trainvache #bellescoccis {
même question sur les ids.

2017-03-27 11:50 UTC, ssipasseuth commented on scripts/install/RegisterPciTrain.php
> +        return $viewDir.implode(DIRECTORY_SEPARATOR, ['js', 'pciCreator', 'train']);
le chemin n'est pas correct... avez-vous testé ce script ?
pour tester, vous pouvez le lancer manuellement en ligne de commande :
```
/var/www/html# sudo -u www-data php index.php 'oat\pciWiquid\scripts\install\RegisterPciTrain'

2017-03-27 11:50 UTC, ssipasseuth commented on scripts/install/RegisterPciTrain.php
> +        return $viewDir.implode(DIRECTORY_SEPARATOR, ['js', 'pciCreator', 'train']);
ce script n'est pas appelé dans le manifest.php, c'est pourtant nécessaire à l'enregistrement de cette pci lors de l'installation de votre extension

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/creator/tpl/markup.tpl
> +</div>
problème d'indentation

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/creator/tpl/markup.tpl
> +<div id="cmdlat" class="cmdlat">
l'usage de l'identifiant ici est-il nécessaire ?

2017-03-27 11:50 UTC, ssipasseuth commented on scripts/update/Updater.php
> +            $this->setVersion('1.1.0');
attention à bien mettre à jour la version de votre extension dans le manifest ou l'update script ne sera pas exécuté

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/runtime/js/renderer.js
> +            if (answccbleue == "non") { $(".trainansw").append(" cocci-ok,");
attention au selecteur jquery global

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/runtime/js/renderer.js
> +            if (answvache == "non") { $(".trainansw").append(" vache-ok,");
selecteur global

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/pciCreator.js
> +        $("div .trainvache").each(function(index, el) {
pourquoi ne pas simplement vider cette fonction. le code commenté n'est plus utile à présent

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/runtime/css/train.css
> +} */
style inutile à supprimer ?

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/runtime/css/train.css
> +@-webkit-keyframes rotating {
il vaut mieux ici aussi mettre un namespace pour vos keyframes pour éviter des collisions avec d'autres définitions

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/runtime/css/train.css
> +@-moz-keyframes rotating {
item

2017-03-27 11:50 UTC, ssipasseuth commented on views/js/pciCreator/dev/train/runtime/css/train.css
> +@keyframes gotrain {
mettre un namespace

2017-03-27 11:50 UTC, ssipasseuth commented on scripts/update/Updater.php
> +            call_user_func(new RegisterPciTrain(), ['0.1.0']);
votre pci passe à la version '1.0.0' comme indiqué sur dans le manifeste pciCreator.json, il convient ainsi de préciser call_user_func(new RegisterPciTrain(), ['1.0.0']);
Pas vital, mais juste une suggestion d'amélioration en passant.
Ceci est applicable aux autres PCIs également (même celles que j'ai oubliées ...)

2017-03-27 12:50 UTC, janfix commented on scripts/update/Updater.php
> +            call_user_func(new RegisterPciTrain(), ['0.1.0']);
Je me suis peut être trompé, mais j'avais compris que je devais modifier le pcicreator.json et mettre la version à 1.1.0 afin que l'update soit pris en compte.
Actuellement le pcicreator.json est en version 1.1.0. Est-ce faux ? Dois-je modifier la ligne 36 ? pour remplacer 0.1.0  par 1.1.0 ?

2017-03-27 13:08 UTC, janfix commented on scripts/update/Updater.php
> +            call_user_func(new RegisterPciTrain(), ['0.1.0']);
à moins que 0.1.0 soit la version de l'extension et non de la PCI

2017-03-27 13:10 UTC, janfix commented on scripts/update/Updater.php
> +            $this->setVersion('1.1.0');
dans le manifest.php la version de l'extension est à 0.1.0 ça devrait être bon ?

2017-03-27 14:08 UTC, ssipasseuth commented on scripts/update/Updater.php
> +            $this->setVersion('1.1.0');
si vous voulez passer de 1.0.0 à 1.1.0. il faut que le manifest.php a pour version 1.1.0

2017-03-27 14:12 UTC, ssipasseuth commented on scripts/update/Updater.php
> +            call_user_func(new RegisterPciTrain(), ['0.1.0']);
voir email pour plus d'info. En résumé, le cycle de vie de l'extension représenté par le manifest.php et le updater.php est différent de celui des PCIs, définie par le pciCreator.json et les appels à leurs scripts de mise à jour `call_user_func(new RegisterPciTrain(), ['0.1.0'])`.

2017-03-28 06:57 UTC, merged

2017-03-28 06:57 UTC, ssipasseuth commented
ok, reste les tests unitaires à compléter