Feature/snap
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #42
Opened 2019-01-21 09:51 UTC by janfix

Voici les dernières modifications de la PCI Snap for TAO. 
Elles concernent : 
a.	Correction du bug sur le redimensionnement de la fenêtre du navigateur
b.	Amélioration de la réactivité de l’affichage lors du chargement d’un import Snap (rafraichissement immédiat de l’éditeur de TAO)
c.	Elargissement de la fenêtre d’affichage de Snap en mode preview et delivery
d.	Mise en place d’un système d’écoute des actions afin de tracer l’activité de l’élève
i.	Attribution d’un numéro d’ordre d’action
ii.	Enregistrement dans l’espace de réponse des intitulés des blocks créés
iii.	Enregistrement du type d’action : Ajout, déplacement, suppression.
e.	Mise en place d’une description textuelle des processus conçus par l’élève
i.	Déclenchement des processus créés par l’élève au moment de la validation de l’item (ne s’ajoute pas au comptage du nombre d’essai)
ii.	Traitement des processus et conversion en une chaîne texte
iii.	Intégration au système de réponse de TAO
f.	Reformatage de la chaine de réponse au format JSON.

J'ai une interrogation sur le fichier js minifié qui n'est pas compilé malgré l'usage du grunt :  il a été unifié, mais sa forme reste lisible. Y -a-t-il un moyen de revenir à sa forme plus réduite afin d'augmenter les performances de la PCI ?

2019-01-23 06:06 UTC, ssipasseuth requested changes
Problème dans le code à plusieurs endroits:
* commentaire manquant
* déclaration des variables avec `var` au début du scope
* toujours pas de test unitaire ? Il est difficile de s'assurer qu'il n'y a pas de régression et de la couverture fonctionnelle demandée dans ce cas.

2019-01-23 06:06 UTC, ssipasseuth commented on scripts/update/Updater.php
> +            $this->setVersion('1.16.1');
Les ajouts fonctionnels doivent correspondre au moins à un changement de version intermédiaire selon le Semantic Versioning. Donc 1.17.0 pour l'ext et 1.1.0 pour snap.

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +            for (let i = 0; i < receiver.length; i++) {
Je ne sais pas si le compilateur fonctionne bien avec la syntaxe de déclaration. Il vaut mieux rester sur du vieux `var` au lieu de `let` pour le moment.

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +            let receiver = snapsrc.snap.world.children[0].stage.children;
il vaut mieux s'assurer que la variable existe avant d'utiliser.

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +            var cleanblockTracker = $container.find(".blockTracker").html();
Il faut déclarer toutes les variables au début du scope de la fonction. (refléter le hoisting)

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +            console.log(countingString);
console.log

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    clientHeight = clientHeight * 0.9; //xdone
que signifie "xdone" dans le commentaire ?

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    let testOrigin = String(this.parent).search("FrameMorph");
`var`

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> + var blockRunner = true; // Allow to write once for receiveCondition -> Block When
commentaire in complet ?

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +var blockRunner = true; // Allow to write once for receiveCondition -> Block When
commentaire in complet ?

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
>  function Process(topBlock, receiver, onComplete, yieldFirst) {
JSdoc manquant pour la fonction Process.
Pourquoi utiliser le majuscule dans le nom de la fonction. La convention est le camel case.

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/renderer.js
> +    $container.find(".snapy").html("");
utiliser une fonction plus explicite `$container.find(".snapy").empty()` permet d'avoir un code plus clair.

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    function scanChildren(blockToScan) {
jsdoc manquante
function trop longue: est-il possible de découper en plusieurs, plus petites, pour faciliter la lisibilité du code ?

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    }
Pourquoi catcher ici ?

2019-01-23 06:06 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    }
Pourquoi catcher ici ?

2019-01-23 06:21 UTC, ssipasseuth commented
Aurais-tu des exemples de projets "complexes" Snap que je pourrais utiliser pour tester ?

2019-01-23 06:32 UTC, ssipasseuth commented
Concernant le problème de compilation de la PCI Snap, je vois en effet que la source n'a pas été minimifiée.
J'ai relancé le script de compilation en local et j'obtiens le même résultat. J'ai donc vérifier les autres PCIs dans https://github.com/oat-sa/extension-tao-itemqti-pci/tree/c186178b8c128d3a03a5031b01dc09bbe2aa5d57/views/js/pciCreator/dev par exemples. Elles sont toutes bien minimifiées.
Je pense qu'il faudrait trouver une solution à ce problème. Par le que le fichier min pèse plus de 2MB et ça risquerait de poser des problèmes dans certaines écoles avec un faible débit internet.
Je te conseil de regarder ce qui est différent dans Snap. Et peut-être tester en retirant tous les fichier et inclure les fichiers un à un et tester la compilation à chaque fois. (même si la PCI ne fonctionnera pas, c'est juste pour tester la compilation).
Sinon pour info, le script de compilation se trouve au https://github.com/oat-sa/extension-tao-itemqti/blob/35f2670331bbb0c0d27dfe608b6faa056c2f4d05/views/build/grunt/portableelement.js#L40-L56
Une autre possibilité et de jouer avec les paramètres de compilation directement dans le script.

2019-01-23 06:34 UTC, ssipasseuth commented
Sinon à la preview, j'ai remarqué un problème de décalage.
![2019-01-23_07-33-07](https://user-images.githubusercontent.com/8425344/51587514-41af6780-1ee1-11e9-803c-ad6c4c4020ae.png)

2019-01-23 08:54 UTC, janfix commented on scripts/update/Updater.php
> +            $this->setVersion('1.16.1');
Exact. J'ai changé la version de snap pour la 1.1.0, la version de l'extension devient 1.17.0. J'ai également changé pour la PCI explorer : la version de l'extension devient la 1.18.0

2019-01-23 09:03 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +            for (let i = 0; i < receiver.length; i++) {
Ok let->var.

2019-01-23 09:04 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +            let receiver = snapsrc.snap.world.children[0].stage.children;
OK je mets tout en tête.

2019-01-23 09:04 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +            var cleanblockTracker = $container.find(".blockTracker").html();
fait

2019-01-23 09:04 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +            console.log(countingString);
supprimé

2019-01-23 09:44 UTC, janfix commented
Les scripts des professeurs sont assez simples, pour le moment ils n'ont qu'un seul sprite. J'ai fait des tests avec des scripts simples, que j'ai réalisé moi-même.
[TwoSprites.zip](https://github.com/janfix/Extension-Wiquid---TAO-DEPP-PCI/files/2786573/TwoSprites.zip)
Puis j'ai testé avec quelques exemples du site comme le swimmer.
s
[swimmer.zip](https://github.com/janfix/Extension-Wiquid---TAO-DEPP-PCI/files/2786579/swimmer.zip)



.

2019-01-23 10:16 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    clientHeight = clientHeight * 0.9; //xdone
Je change le comment pour : define height/width of snap

2019-01-23 10:16 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    let testOrigin = String(this.parent).search("FrameMorph");
OK pour var

2019-01-23 10:21 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> + var blockRunner = true; // Allow to write once for receiveCondition -> Block When
Non le commentaire est bien complet mais peu clair. 
Le block When de Snap est particulier, il est un listener, si je ne prends pas la précaution de vérifier que je l'ai écrit une fois, il s'écrit de nombreuses fois.

2019-01-23 10:22 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +var blockRunner = true; // Allow to write once for receiveCondition -> Block When
idem, il s'agit du block When

2019-01-23 10:54 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
>  function Process(topBlock, receiver, onComplete, yieldFirst) {
Cette fonction est native dans Snap, j'y ai introduit mon code pour pister les processus. Je n'ai donc pas choisi son nom. Elle permet depuis un topblock de lancer l'enchaînement des autres blocks par le truchement des attributs de l'objet en cours. 
Je propose le commentaire suivante : 
/** The function Process starts the chaining of blocks depending on the receiver(usually the sprite) - Spying the process (to put them in text string) is here possible  **/

2019-01-23 10:59 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/renderer.js
> +    $container.find(".snapy").html("");
OK je le mets partout !

2019-01-23 11:13 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    function scanChildren(blockToScan) {
Je propose pour le jsdoc : /*scanBlock check the nature of each block in process and organize the information to translate it in a readable string  */
Je préfère conserver l'unité de cette fonction qui est partiellement récursive : la subfunction slotClosure vérifie si on est dans un contenant pour pouvoir le fermer. Puis une boucle analyse le block et récupère le texte de description. Afin de parcourir l'ensemble des processus, la fonction est auto-rappelée au niveau des éventuels enfants. Puis un système de correction aménage la string qui relate l'ensemble des blocks enchaînés.

2019-01-23 11:15 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    }
J'évite toute erreur sur la redimension de la fenêtre.

2019-01-23 11:15 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    }
idem

2019-01-23 15:23 UTC, janfix commented
Concernant le décalage, chez moi c'est parfaitement centré. Mais la fenêtre de Snap sur ton screenshot me semble plus petite que sur mon écran. C'était une demande de la DEPP : un plus large espace de travail ... Je vais voir comment régler ça.

2019-01-24 10:30 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
>  function Process(topBlock, receiver, onComplete, yieldFirst) {
ah ok, si c'est natif, tu peux le laisser en état donc. Il faut juste préciser dans l'entête, sous la license, les changements apportés par tes soins.

2019-02-08 15:07 UTC, janfix commented
Bonjour Sam, 
Je pense avoir pas mal bonifié les codes des deux PCI. Elles sont maintenant dispo sur Github.
Concernant Snap tu peux voir dans les commentaires les modifications suite à tes remarques. De mon côté, j'ai amélioré la fonction d'affichage du canvas qui est proportionnelle maintenant à la zone d'affichage. Toutefois, sur un écran très large, la marge à gauche est conséquente car  j'ai choisi l'alignement à gauche respectant les marges des autres items de l'évaluation, pour gagner de la place Snap prend de l'espace sur la droite ce qui permet de maximiser l'affichage.
Une autre amélioration sur Snap et Explo : la compilation. Les erreurs de compilations qui stoppaient le script après l'unification des js étaient dues à la présence de quelques éléments ECMAScript 6. J'ai utilisé un outil en ligne pour mettre en évidence les points de blocage. 
Concernant explorer, j'ai encore amélioré le code, mais j'ai conscience de ne pas avoir respecté à la lettre la contrainte du hoisting.  Pour ce qui est de la structure pas assez transparente, j'ai essayé de faire un effort sur les commentaires en utilisant le jsdoc (qui est super et je te remercie de m'avoir poussé à l'utiliser). Je te fais passer par les commentaires de la PR d'explo la liste des tests fonctionnels que j'ai utilisé. J'ai un mal fou à me mettre à l'outil de test unitaire, mais devant les difficultés que j'ai rencontré avec Explorer, j'ai décidé qu'il était urgent de m'y mettre, ça ne pourra qu'améliorer ma production.
J'attends avec impatience tes remarques qui sont toujours autant d'occasion d'améliorer mon travail.
Bon courage. Je reste à ta disposition en cas de besoin.

2019-02-13 05:42 UTC, ssipasseuth commented
Est-ce que DEPP trouve acceptable que la taille de snap soit fixé au chargement de la page et la modification de la fenêtre ensuite ne redimensionne pas snap, ce qui fait qu'on peut éventuellement avoir le snap caché. Pour certains clients ça peut être considérer comme un bug. Donc est-ce qu'on peut avoir une confirmation de DEPP que c'est ok ?
![2019-02-13_06-42-30](https://user-images.githubusercontent.com/8425344/52689469-8cf5ec80-2f5a-11e9-9ced-e2b4dec726c9.png)


Sinon pour les tests unitaires, est-ce que tu vas l'ajouter dans cette PR ? Selon notre guideline, on ne peut normalement pas accepter de PR sans test unitaire.

2019-03-25 17:37 UTC, ssipasseuth requested changes
Fonctionnellement ok. Mis à part le décalage décrit plus haut. Mais si le client accepte ce bug pour le moment, on peut partir dessus.
Il y a des blocks de code commenté et je me demande l'utilité de les conserver du coup. Pourquoi pas les supprimer ? (si besoin, ils pourront être retrouvé dans l'historique des commits)

2019-03-25 17:37 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +           // value = "{\"actions\": {" + cleanblockTracker + "}," + "\"processus\":[" + cleanProcessus + "]" + countingString + "\"snapImage\" : \"" + "dataURL" + "\"keyLog\": {" +snapsrc.keyLog +"}
Code commenté à supprimer

2019-03-25 17:37 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/css/SnapForTao.css
> +  margin-right: auto !important; */
code commenté à supprimer

2019-03-25 17:37 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    console.log(button);
console.log

2019-03-25 17:37 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    ); */
code inutile à supprimer ?

2019-03-25 17:37 UTC, ssipasseuth commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +        );*/
code inutile à supprimer ?

2019-03-27 08:31 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/SnapForTao.amd.js
> +           // value = "{\"actions\": {" + cleanblockTracker + "}," + "\"processus\":[" + cleanProcessus + "]" + countingString + "\"snapImage\" : \"" + "dataURL" + "\"keyLog\": {" +snapsrc.keyLog +"}
OK c'est supprimé !

2019-03-27 08:31 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/css/SnapForTao.css
> +  margin-right: auto !important; */
OK c'est supprimé !

2019-03-27 08:32 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    console.log(button);
OK c'est supprimé !

2019-03-27 08:38 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +    ); */
OK c'est supprimé !

2019-03-27 08:39 UTC, janfix commented on views/js/pciCreator/dev/snap/runtime/js/lib/snapsrc.js
> +        );*/
OK c'est supprimé !

2019-03-27 09:41 UTC, janfix commented
Bonjour Sam, 
Le décalage d'affichage est OK pour la DEPP c'était une solution bricolée mais efficace pour augmenter la surface de Snap si l'écran est plus large (existence de marge).
J'ai supprimé tous les codes commentés. Effectivement, je voulais laisser dans le code les lignes consacrées aux Customs Blocks. Mais le groupe de concepteurs a voulu simplifier encore l'interface et escamoter ce bouton qui n'a pas d'utilité pour eux... Au besoin je fouillerai dans l'historique des commits.  Je te remercie pour cette review super rapide.
Je préviens la DEPP de la future intégration à l'extension en mode Master.

2019-05-09 07:15 UTC, ssipasseuth commented
A part le problème de taille évoquée plus haut, ça semble fonctionner.

2019-05-09 07:16 UTC, merged