Modification de Berthold :
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #6
Opened 2017-02-27 13:53 UTC by janfix

Ce que je n'ai pas fait : améliorer le code en créant une fonction média dans laquelle j'injecte les coordonnées des médias à afficher. Je l'ai faite dans cuisine, je vous la poste aussi.

**Ci-dessous ce qui est fait**

 Format icones - OK

 Suppression logs - OK

 Commentaires en anglais OK

Licence : Pas encore envoyé par la DEPP

setSerializedState / Non traité
getSerializedState

Supprimer les codes
commentés - OK

Pas d'anglais dans
l'encodage des réponses - OK

CSS scopés
qti-customInteraction .nom-de-votre-pci .selector {css rule} -OK

Nettoyer vieux
CSS likert - OK

Indentation
Du code -OK

Triple signe égal pour les comparaisons -OK

 supprimer les variables non utilisées - OK

 Eviter les id : -OK

 Minimiser les constructions objet Jquery OK

Principe Dry : fonction plutôt que répétition : OK ? (à améliorer ?)

Eviter fade In privilégier les transitions CSS : OK

Supprimer les propriétés PCI non applicable : OK

Eviter les balises de style dans le markup : OK

Escamoter des éléments au drop dans l'éditor : La PCI déborde, au clic je fais disparaître ce qui déborde.

Use strict : non appliqué / à faire

Verifier la version : 1.1.0

Ajout du code anti-duplication dans le même item ? OK

Corriger les Widgets et les scories likert : OK

Edge : pas de problème d'affichage

2017-02-27 16:16 UTC, ssipasseuth requested changes
Les mêmes types de problèmes que dans l'autre PR https://github.com/janfix/Extension-Wiquid---TAO-DEPP-PCI/pull/7 appraissent ici.
Il a encore des copiés/collés depuis likert interaction.
Le test unitaire est manquant.

2017-02-27 16:16 UTC, ssipasseuth commented on views/js/pciCreator/dev/Berthold/runtime/js/renderer.js
> +        var $suivant1 = $(".suivant1");
Les déclarations des variables doivent être en début du scope pour refléter le hoisting des variables: https://www.w3schools.com/js/js_hoisting.asp

2017-02-27 16:16 UTC, ssipasseuth commented on views/js/pciCreator/dev/Berthold/test/commonRenderer.html
> +<html>
test unitaire, copier/coller depuis likert interaction

2017-02-27 16:16 UTC, ssipasseuth commented on views/js/pciCreator/dev/Berthold/runtime/css/base.css
> +.qti-customInteraction .likertScaleInteraction{
css d'une autre interaction  ??

2017-02-27 16:16 UTC, ssipasseuth commented on views/js/pciCreator/dev/Berthold/pciCreator.json
> +            "./runtime/css/base.css",
base.css d'une autre interaction

2017-02-27 16:16 UTC, ssipasseuth commented on views/js/pciCreator/dev/Berthold/pciCreator.json
> +            "./runtime/assets/img1.svg",
il vaut mieux privilégier un nom plus explicite

2017-02-27 16:16 UTC, ssipasseuth commented on views/js/pciCreator/dev/Berthold/runtime/css/Berthold.css
> +}
attention aux indentations irrégulières partout dans la css

2017-03-03 09:09 UTC, janfix commented on views/js/pciCreator/dev/Berthold/runtime/js/renderer.js
> +        var $suivant1 = $(".suivant1");
Mais l'instanciation des médias doit avoir eu lieu pour leur attribuer une class. Je peux alors les variabiliser.

2017-03-03 09:09 UTC, janfix commented on views/js/pciCreator/dev/Berthold/test/commonRenderer.html
> +<html>
Je ferai les tests unitaires tous ensemble.

2017-03-03 09:11 UTC, janfix commented on views/js/pciCreator/dev/Berthold/runtime/css/base.css
> +.qti-customInteraction .likertScaleInteraction{
Vu, j'efface !

2017-03-03 09:14 UTC, merged