Suivi de PCI - Cuisine
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #7
Opened 2017-02-27 14:19 UTC by janfix

**A faire ou améliorer :** 
Non fait : compatbilité Edge, j'ai un décallage avec le Boiler,
Minimiser les appels jquery : fait partiellement,
L'enchainement des fadeIn / fadeOut est très commode, à cause des delay, c'est plus facile à gérer est-ce vraiment rédibitoire ?

**Ce qui est fait :**
 Format icones -OK

 Suppression logs -OK

 Commentaires en anglais -OK

Licence : Pas encore

setSerializedState / Non traités
getSerializedState

Supprimer les codes
commentés - OK

Pas d'anglais dans
l'encodage des réponses - OK

CSS scopés
qti-customInteraction .nom-de-votre-pci .selector {css rule} OK

Nettoyer vieux
CSS likert - OK

Indentation
Du code - OK

Triple signe égal pour les comparaisons : OK

 supprimer les variables non utilisées : OK

 Eviter les id : tous les ID ont été virés !

 Minimiser les constructions objet Jquery : OK pour la création des médias

Principe Dry : fonction plutôt que répétition :OK pour la création des médias

Eviter fade In privilégier les transitions CSS : L'enchainement des fadeIn / fadeOut est bcp plus simple à gérer avec les delays

Supprimer les propriétés PCI non applicable : OK

Eviter les balises de style dans le markup : OK

Escamoter des éléments au drop dans l'éditor : non

Use strict : pas encore

Verifier que la version 1.1.0 dans le Json OK

Ajout du code anti-duplication dans le même item ? OK

Corriger les Widgets et les scories likert OK

Edge : le boiler est 1 image décallée ! CSS spécifique à faire

2017-02-27 15:57 UTC, ssipasseuth requested changes
Le manifest.php n'a pas été mis à jour avec la nouvelle version de l'extension ainsi que l'enregistrement de la PCI.

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/css/cuisine.css
> +.qti-customInteraction .boiler2{
manque le ns .cuisine

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/css/cuisine.css
> +        }
indentation étrange

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/css/cuisine.css
> +    }
indentation

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/pciCreator.js
> +        },
methode optionnelle non implémentée donc peut être simplement supprimé

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/creator/widget/states/Question.js
> +*/
code commenté inutile

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/creator/widget/states/Question.js
> +
'use strict'

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/creator/widget/Widget.js
> +
'use strict'

2017-02-27 15:57 UTC, ssipasseuth commented on scripts/update/Updater.php
>   */
header à revoir en fonction de la licence finale

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/cuisine.amd.js
> +          //  $container.find('input[value="' + value + '"]').prop('checked', true); // trouve le input dont la valeur est value et le met sur true !
code commenté...

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/cuisine.amd.js
> +                value = $(".cuisineasw").text();
selecteur global $(".cuisineasw") à éviter, il vaut mieux toujours ajouter le context : $container.find('.cuisineasw');

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +
'use strict'

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +        var $ztartre = $(".zonetartre");
context de sélection à préciser $container.find('.zonetartre');

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +        var $zboiler = $(".zoneBoiler");
idem

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +        var $zfeu = $(".zonefeu");
idem

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +        var $zchoco = $(".zonechocolat");
idem

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +            $(".cuisine").append("<button class='bt bt-tartre'>Observation n°4</button><button class='bt bt-boiler'>Observation n°1</button><button  class='bt bt-feu'>Observation n°3</button><button
idem, et pour le reste du fichier

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +            console.log(zone + " " + z_assets + " " + z_text);
console.log à retirer

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +        var zboiler_text ="<div class='boilertxt'>L'eau bout dans la bouilloire</div>" ;
espace entre opérateur inconsistant

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +            answboiler = "bouilloire";
la variable answboiler semble jouer le role d'une constante.... pourquoi ne pas déclarer sa valeur answboiler plus haut ?

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/cuisine.amd.js
> +//          var assetManager = qtiCustomInteractionContext.getAssetResolver(this.getTypeIdentifier());//that would introduce dependency between the asset manager and global pci runtime context
code commenté

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/cuisine.amd.js
> +        initialize : function(id, dom, config, assetManager){
il est conseillé de nommer les fonctions : initialize : function **initialize**(id, dom, config, assetManager){...}
http://stackoverflow.com/questions/15336347/why-use-named-function-expressions

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +
beaucoup de sélecteurs globaux et d'objets jquery réinstanciés. Que diriez-vous de les grouper ensemble comme ceci ?
```
var $element = {
    tartre1 : $container.find('. tartre1'),
    tartre2 : $container.find('.tartre2'),
    vinaigre : $container.find('. vinaigre'),
    tartretxt : $container.find('. tartretxt'),
}

$element.tartre2.hide();
$element.tartre1.hide();

2017-02-27 15:57 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +
saut de ligne inutile ?

2017-02-27 16:04 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/runtime/cuisine.amd.js
> +        setResponse : function(response){// Fait passer la réponse à la fonction. La var response est définie dans question.js
commentaire toujours en français

2017-02-27 16:04 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/creator/tpl/propertiesForm.tpl
> +  <p>Réalisation <a href='http://www.wiquid.fr'>Wiquid</a></p>
A ouvrir dans une nouvelle fenêtre ou onglet avec target="_blank" sinon l'utilisateur quitte l'outil d'authoring et peut perdre son travail ce qui peut être frustrant.
Question politique : le client est-il d'accord d'avoir votre lien ici ?

2017-02-27 16:19 UTC, janfix commented on views/js/pcicreator/dev/cuisine/runtime/js/renderer.js
> +            answboiler = "bouilloire";
Elle sert à vérifier si l'élève a activé l'animation, donc elle prend la valeur de la bouilloire, du chocolat, du feu et du tartre.

2017-02-27 16:19 UTC, ssipasseuth commented
pas de test unitaire ?

2017-02-27 16:22 UTC, janfix commented on views/js/pcicreator/dev/cuisine/creator/tpl/propertiesForm.tpl
> +  <p>Réalisation <a href='http://www.wiquid.fr'>Wiquid</a></p>
Je vérifie tout de suite auprès de la DEPP.

2017-03-01 08:16 UTC, janfix commented on views/js/pcicreator/dev/cuisine/creator/tpl/propertiesForm.tpl
> +  <p>Réalisation <a href='http://www.wiquid.fr'>Wiquid</a></p>
La DEPP est OK, j'ai mis le target="_blank".

2017-03-01 10:16 UTC, ssipasseuth commented on views/js/pcicreator/dev/cuisine/creator/tpl/propertiesForm.tpl
> +  <p>Réalisation <a href='http://www.wiquid.fr'>Wiquid</a></p>
ok

2017-03-03 09:01 UTC, closed without merging

2017-03-03 09:03 UTC, janfix reviewed
Ok c'est fait !