Feature/abeille
janfix/Extension-Wiquid---TAO-DEPP-PCI pull request #8
Opened 2017-03-03 11:22 UTC by janfix

2. Signature Wiquid fixed (open blank)
3. use strict
4. commented code deleted
5. Non-Anonymous function in AMD on initialize
6. $Container.find OK
7. less call on jQuery objects
8. Unique ID with Lodash

2017-03-06 14:19 UTC, ssipasseuth reviewed
il serait bien d'ajouter la licence+propriété intellectuelle dans l'entête du fichier

2017-03-06 14:19 UTC, ssipasseuth commented on views/js/pciCreator/abeille/creator/widget/states/Question.js
> +        $(".cmdpanel").hide();
selecteur global à éviter au profit de $container.find('.cmdpanel');

2017-03-06 14:19 UTC, ssipasseuth commented on views/js/pciCreator/abeille/creator/widget/states/states.js
> +
use strict

2017-03-06 14:19 UTC, ssipasseuth commented on views/js/pciCreator/abeille/pciCreator.js
> +
use strict

2017-03-06 14:19 UTC, ssipasseuth commented on views/js/pciCreator/abeille/pciCreator.js
> +    //all libs should be declared here
commentaire inutile "all libs should be declared here"

2017-03-06 14:19 UTC, ssipasseuth commented on views/js/pciCreator/abeille/runtime/abeille.amd.js
> +
use strict

2017-03-06 14:19 UTC, ssipasseuth commented on views/js/pciCreator/abeille/test/commonRenderer.html
> +</html>
unit test copié collé depuis likerScaleInteraction

2017-03-06 14:19 UTC, ssipasseuth commented on views/js/pciCreator/abeille/test/commonRenderer.html
> +</html>
pas de test unitaire pour PCI abeille ?

2017-03-06 14:19 UTC, ssipasseuth commented on views/js/pciCreator/abeille/creator/tpl/markup.tpl
> +	<div class="frelonclick hiddendiv"></div>
pas très grave mais indentation étrange

2017-03-08 09:03 UTC, janfix commented on views/js/pciCreator/abeille/creator/tpl/markup.tpl
> +	<div class="frelonclick hiddendiv"></div>
espace à la place de Tab, c'est corrigé.

2017-03-28 10:20 UTC, ssipasseuth requested changes
encore quelques soucis à régler

2017-03-28 10:20 UTC, ssipasseuth commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +            var otherslider = $('.frelonslider').val();
1. hoisting de la variable _otherslider_
2. selecteur global

2017-03-28 10:20 UTC, ssipasseuth commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +                var actionbee = 8 - beepresente;
hoisting de la variable actionbee

2017-03-28 10:20 UTC, ssipasseuth commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +                for (var i = 0; i < group1.length; i++) {
var i delcarée plusieurs fois... il ne faut le faire qu'une fois, en début de scope l.163 et l'utiliser directement ensuite. Pour éviter la déclaration de ce type de variable, vous pouvez utiliser OAT/lodash _.each().

2017-03-28 10:20 UTC, ssipasseuth commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +            if (eval(this.value) === 1 && eval(otherslider) === 0) {
L'utilisation de eval est une mauvaise pratique: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/eval
Ici parseInt() suffit largement.

2017-03-28 10:20 UTC, ssipasseuth commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +            if (eval(this.value) === 0 && eval(otherslider) === 1) {
eval à remplacer par parseInt

2017-03-28 10:20 UTC, ssipasseuth commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +                    blueset[group1[i]].animate({ "opacity": "0" }, 2000); // Disappearance of 25%
n'est-il pas plus judicieux d'utiliser les transition css3 ici (et partout ailleurs dans ce fichier) ?

2017-03-28 10:20 UTC, ssipasseuth commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +                }
beaucoup de bloc copié/collé ici... il serait plus judicieux de créer des fonctions réutilisable: hideGroup(group), showGroup(); votre code sera plus lisible et maintenable.

2017-03-28 10:20 UTC, ssipasseuth commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +            if (eval(this.value) === 0 && eval(otherslider) === 2) {
est-ce que vous pouvez documenter rapidement ce que représente chacun de ces cas "if" ?

2017-03-28 11:28 UTC, janfix commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +            var otherslider = $('.frelonslider').val();
Ok corrigé.

2017-03-28 11:35 UTC, janfix commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +                    blueset[group1[i]].animate({ "opacity": "0" }, 2000); // Disappearance of 25%
J'ai suivi les instructions de la doc Raphael JS

2017-03-28 11:52 UTC, janfix commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +            if (eval(this.value) === 0 && eval(otherslider) === 2) {
Il s'agit des 3x3 positions des 2 sliders combinées. 0 et 1, 1 et 1, ...2 et 2

2017-03-28 11:54 UTC, janfix commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +            if (eval(this.value) === 0 && eval(otherslider) === 2) {
Les boucles for font disparaitre les fleurs

2017-03-28 12:36 UTC, janfix commented on views/js/pcicreator/dev/abeille/runtime/js/renderer.js
> +                }
OK j'ai crée les 2 fonctions et je les ai intégrées aux cas if..

2017-03-28 13:43 UTC, merged

2017-03-28 13:44 UTC, ssipasseuth commented
Ok, il ne manque plus que les tests unitaires